name: cs325b
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - cudatoolkit=11.3
  - pytorch=1.12.1
  - torchvision=0.13.1
  - torchaudio=0.12.1
  - gdal
  - pip
  - pip:
    - matplotlib
    - torchmetrics
    - pytorch_lightning
    - segmentation_models_pytorch
    - einops
    - dask
    - rioxarray
    - rasterio
    - planetary_computer
    - pystac_client
    - adlfs
    - stackstac
    - geopandas
    - dask
    - distributed
    - netCDF4
    - scipy
    - tqdm